# Generated by Django 4.1.3 on 2023-07-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=18)),
                ('email', models.CharField(default='', max_length=50)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('interests', models.JSONField()),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='users.user')),
                ('friends', models.ManyToManyField(blank=True, to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
