# Generated by Django 4.1.3 on 2023-07-14 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_delete_topic_alter_topicsofinterest_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=18)),
                ('email', models.CharField(default='', max_length=50)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='users.profile')),
                ('friends', models.ManyToManyField(blank=True, to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
