# Generated by Django 4.2.5 on 2023-10-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
