# Generated by Django 4.2.5 on 2023-10-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
